### ISSUE TITLE
Remove the Louis.Logging library

### ISSUE THREAD

**Issue by ric15ni** [Tenacom/Louis#79]
### Reference version

1.0.152-preview

### Background and motivation

The `Louis.Logging` library contains some interesting code. (I can write a string interpolation handler, yay for me!) However, it encourages bad practices (not using unique event IDs). Besides, its usefulness is questionable since .NET 6 introduced the [LoggerMessage attribute](https://learn.microsoft.com/en-us/dotnet/core/extensions/high-performance-logging).

The development of `Louis.Logging` stemmed from the need to port code using our internal logging library `Tenalog` to .NET Core, using Microsoft's extensions libraries and Community Toolkit, as quickly and effortlessly as possible. Tenalog has no concept of event IDs, so they were completely overlooked in the development of the `LoggerExtensions` class.

The other feature of `Louis.Logging`, namely the `PrefixingLogger` class, is nothing more than a poor substitute for context data. It was born to mimic a feature of Tenalog, which has no concept of context data.

Now that I have a better understanding of `Microsoft.Extensions.Logging`, I see `Louis.Logging` for what it is: a quick and dirty "bridge" from Tenalog to Microsoft.Extensions.Logging, that should have always been marked "internal use only".  
(Speaking of internal use, there are currently no Tenacom projects using `Louis.Logging`: `LoggerMessage` and context data FTW!)

I therefore propose that `Louis.Logging` be removed before L.o.U.I.S. reaches version 1.0.

### Proposed enhancement

Remove the `Louis.Logging` library. The world will be a better place without it.

### Implementation proposals

Zap the project, deprecate the NuGet package.

### Usage examples

_(n/a)_

### Risks

No risks, as no code is currently using `Louis.Logging`.

**Comment by rdeago** [comment]
> [...] Tenalog has no concept of event IDs, so they were completely overlooked in the development of the `LoggerExtensions` class.

> [...] Tenalog [...] has no concept of context data.

In defense of Tenalog, it works like a charm. It has been serving us well for eight years, without any major (nor otherwise) issue.

That having been said, the world has moved on. Adapting Tenalog to interface with Microsoft.Extensions.Logging would mean weeks of work to obtain... what, exactly? Another Serilog, but without its ecosystem? No, thanks.

The effort to get rid of Tenalog has been huge (and is still not over). In the course of such effort, we messed up. Badly. In public. I agree that `Louis.Logging` should not have been part of L.o.U.I.S. to start with: it should have been its own internal library instead.

So, to cut a long (and painful) story short: go for it! :+1:
